### ISSUE TITLE
treatAsLanguageTagged

### ISSUE THREAD

**Issue by pkiraly** [pkiraly/metadata-qa-api#188]
In Europeana's JSON output the language tag is not annotated with a distinct property, such as `@lang`, but as key in associated array:

```json
"dcTitle": {
  "la": [
    "Sonus naturalis"
  ]
},
```
There should be a property on schema level or on field level, to treat this structure as language tagged strings:

```yaml
fields:
  - path: dcTitle
    treatAsLanguageTagged: true
```
