### ISSUE TITLE
hasLanguageTag checker

### ISSUE THREAD

**Issue by pkiraly** [pkiraly/metadata-qa-api#194]
It should check if the data element has language attribute. I should have the following values:

* `allOf`: all instances should have language attribute
* `anyOf`: at least one instance should have language attribute
* `oneOf`: only instance should have language attribute

An example:

data:

```json
{
  "id":"Portrait",
  "description":{
    "de":["Portr\u00e4t"],
    "zh":["\u8096\u50cf"]
  }
}
```
schema:
```yaml
format: JSON
fields:
 - name: description
   path: $.['description']
   asLanguageTagged: true
   rules:
     - hasLanguageTag: allOf
```
