### ISSUE TITLE
Map Avram to MQA Schema

### ISSUE THREAD

**Issue by nichtich** [pkiraly/metadata-qa-api#210]
I think we can map an [Avram schema](https://format.gbv.de/schema/avram/specification) of [format family `flat`](https://format.gbv.de/schema/avram/specification#format-families) (e.g. CSV files) to a corresponding MQA Schema. Avram schemas for MARC and PICA would first require addition of these formats and their locator languages (`path`) to metadata-qa-api.

**Comment by pkiraly** [comment]
@nichtich Sorry, I do not really get the idea. Could you add an example for the CSV file?

**Comment by nichtich** [comment]
Sample flat record from Avram specification:

~~~json
{
  "fields": [
    { "tag": "given", "value": "Henriette" },
    { "tag": "given", "value": "Davidson" },
    { "tag": "surname", "value": "Avram" },
    { "tag": "birth", "value": "1919-10-07" }
  ]
}
~~~

Same in CSV (with non-standard internal separator '|'):

~~~csv
given,surname,birth
Henriette|Davidson,Avram,1919-10-07
~~~

Sample Avram schema

~~~json
{
  "family": "flat",
  "fields": {
    "given": {
      "label": "given name",
      "required": false,
      "repeatable": true
    },
    "surname": {      
      "required": true,
      "repeatable": true
    },
    "birth": {
      "description": "date of birth in YYYY-MM-DD format",
      "required": false,
      "repeatable": false,
      "pattern": "^[0-9-]+$"
    }
  }
}
~~~

Could be an MQA Schema as well.

Hoever flat CSV files are rarely validated at all in practice. Either you get dirty CSV or you get more format data but then its not CSV but JSON, XML or some other format.

**Comment by pkiraly** [comment]
Thanks for the example, now it is clear. The sample Avram schema could be transformed to MQA schema as:

```yaml
format: CSV
fields:
  - path: given
    name: given name
    rules:
    - minCount: 0
  - path: surname
    name: surname
    rules:
    - minCount: 1
  - path: birth
    name: birth
    description: date of birth in YYYY-MM-DD format
    rules:
    - minCount: 0
    - pattern: ^\\d{4}-\\d{2}-\\d{2}$
```

In that simple case the translation is straightforward. Do you have a repository that contains full examples of those flat schemas, that I could use as the base inputs for a Avram2MQA "translation" class?
