### ISSUE TITLE
Change mqafPattern to accept list instead of single string

### ISSUE THREAD

**Issue by pkiraly** [pkiraly/metadata-qa-api#224]
```yaml
mqafPattern:
  pattern:
    - a
    - b
    - c
```
It will be transformed as regex "a|b|c".

This is needed because if we have lots of components, maintaining the pattern is getting difficult.
