### ISSUE TITLE
Simple schema language

### ISSUE THREAD

**Issue by mielvds** [pkiraly/metadata-qa-api#51]
While it's worthwhile to implement existing, language specific schema languages like JSONSchema or SHACL, it might be helpful to have a custom, perhaps YAML-based schema language to handle the simple cases. 

A schema reader or parser class would then create a Schema object at runtime. I think this woulb be particularly useful in a compiled language like Java. 

For instance, you could have (from [EdmFullBeanLimitedSchema.java](https://github.com/pkiraly/metadata-qa-api/blob/master/src/main/java/de/gwdg/metadataqa/api/schema/EdmFullBeanLimitedSchema.java) )

``` yaml
format: json
fields:
 - edm:ProvidedCHO/@about:
      path:  $.['providedCHOs'][0]['about']
      categories: MANDATORY
- Proxy/dc:title:
      path: $.['proxies'][?(@['europeanaProxy'] == false)]['dcTitle']
      categories: 
         - DESCRIPTIVENESS
         - SEARCHABILITY
         - IDENTIFICATION
         - MULTILINGUALITY
- Proxy/dcterms:alternative:
      path: $.['proxies'][?(@['europeanaProxy'] == false)]['dctermsAlternative']
      categories: 
         - DESCRIPTIVENESS
         - SEARCHABILITY
         - IDENTIFICATION
         - MULTILINGUALITY

...

groups:
- 
  fields: 
    - Proxy/dc:title
    - Proxy/dc:description
   categories: MANDATORY

...







```

**Comment by pkiraly** [comment]
Hi @mielvds,

it is a good idea!

I started working on it. You can not yet use it, these are just the initial steps. I neer worked YAML previously, and I run into problems, so I made some changes. I am using a YAML library called snakeyaml.

1. I do not know how to map fieldnames as keys. I give an explicit property "name" instead
2. I also do not know how to handle when the categories are sometimes singular and take place in the same line as the property name and sometimes plural and each in distinct line. So I always put them into a distinct line.
3. I thought it is not important to add groups into distinct document, so I removed the document separator (`...`)

Here is the result:

```YAML
format: json
fields:
  - name: edm:ProvidedCHO/@about
    path:  $.['providedCHOs'][0]['about']
    categories:
      - MANDATORY
  - name: Proxy/dc:title
    path: $.['proxies'][?(@['europeanaProxy'] == false)]['dcTitle']
    categories:
      - DESCRIPTIVENESS
      - SEARCHABILITY
      - IDENTIFICATION
      - MULTILINGUALITY
  - name: Proxy/dcterms:alternative
    path: $.['proxies'][?(@['europeanaProxy'] == false)]['dctermsAlternative']
    categories:
      - DESCRIPTIVENESS
      - SEARCHABILITY
      - IDENTIFICATION
      - MULTILINGUALITY
groups:
  - fields:
      - Proxy/dc:title
      - Proxy/dc:description
    categories:
      - MANDATORY
```

Are these changes are acceptable for you? Do you have any suggestion reading YAML with Java? I think that it would worth to build the same for JSON(-LD) (which is more explicit for me for the time being).
