### ISSUE TITLE
Make the Categories configurable

### ISSUE THREAD

**Issue by pkiraly** [pkiraly/metadata-qa-api#59]
@mielvds suggested the following: Would it be an idea to enable custon extentions of this list with arbitrary groups?

Right now category is an enumeration, and can not be configured.

**Comment by mielvds** [comment]
yep, that'll work!

**Comment by pkiraly** [comment]
@mielvds 

I have two ideas, I would like to ask you your opinion.

Case 1: the categories on the field level is arbitrary, so you can add anything you want, there is no check at all.

Case 2: you should either add a "categories" list on schema level as well, which contains all possible values. It behaves as a controlled vocabulary, and the field level category MUST BE in this list.

Here is an example for Case 2:
```yaml
format: json
fields:
  - name: edm:ProvidedCHO/@about
    path:  $.['providedCHOs'][0]['about']
    categories:
      - MANDATORY
  - name: Proxy/dc:title
    path: $.['proxies'][?(@['europeanaProxy'] == false)]['dcTitle']
    categories:
      - DESCRIPTIVENESS
      - SEARCHABILITY
      - IDENTIFICATION
      - MULTILINGUALITY
      - CUSTOM
  - name: Proxy/dcterms:alternative
    path: $.['proxies'][?(@['europeanaProxy'] == false)]['dctermsAlternative']
    categories:
      - DESCRIPTIVENESS
      - SEARCHABILITY
      - IDENTIFICATION
      - MULTILINGUALITY
groups:
  - fields:
      - Proxy/dc:title
      - Proxy/dc:description
    categories:
      - MANDATORY
categories:
  - MANDATORY
  - DESCRIPTIVENESS
  - SEARCHABILITY
  - IDENTIFICATION
  - MULTILINGUALITY
  - CUSTOM
```

Note the categories in the last section. It give the schema create a bit more work, but keep the consistency of the categories. If it is missing the default list which the tool will compare the field categories against will be the current enumeration.

Would you vote for case 1 or case 2?
