### ISSUE TITLE
Relationship between categories in fields and groups

### ISSUE THREAD

**Issue by atiro** [pkiraly/metadata-qa-api#71]
I was looking to implement the support for the yaml config loading up fields groups but I've got a bit confused between categories in field groups and categories in fields. I don't think they have any connection, if I'm reading the code right ?

That works for me in one way as I would like to be able to say "if any field in this group exists, the category completeness is 1", but 
ideally I would have also liked to be able to say something like "treat just these 3 fields as a group" within a set of 10 fields, I don't
think that's possible though?

**Comment by pkiraly** [comment]
@atiro Maybe I am not clearly understand your request, but I think your requirement can be expressed. Let's see this schema:

```yaml
fields:
  - name: title
  - name: description
  - name: image
    categories: [optional]
  - name: link
  - name: license
groups:
  - fields: [title, description]
    categories: [mandatory]
  - fields: [link, license]
    categories: [optional]
```
There are in total 2 categories. One (optional) is bound to a field and a field group, the other (mandatory) is bound to a field group. I guess that is what you need.

* "if any field in this group exists, the category completeness is 1" -- if either title or description exists mandatory will be 1:

| title | description | score of `mandatory` category |
| --- | --- | --- |
| 0 | 0 | 0 |
| 1 | 0 | 1 |
| 1 | 1 | 1 |
| 0 | 1 | 1 |

* if a group is not the only part of a category, then the situation is more complex:

| image | link | license | score of `optional` category |
| --- | --- | --- | --- |
| 0 | 0 | 0 | 0 |
| 1 | 0 | 0 | 0.5 |
| 1 | 1 | 0 | 1 |
| 1 | 1 | 1 | 1 |
| 0 | 1 | 0 | 0.5 |
| 0 | 0 | 1 | 0.5 |
| 0 | 1 | 1 | 0.5 |

**Comment by atiro** [comment]
Hi @pkiraly I think I follow that, but now I think I may have got the whole use of categories wrong! I have been using it to group fields together with conceptual names, e.g.

```
    - name: artistMakerPerson
      categories:
          - PRODUCTION
    - name: artistMakerOrganisation
      categories:
          - PRODUCTION
    - name: artistMakerPeople
      categories:
          - PRODUCTION
    - name: placesOfOrigin
      categories:
          - PRODUCTION

```
which works with categories scoring at the field level, but I think for field groups the categories have to be one of the enum types such as OPTIONAL, MANDATORY ? That only then works if those are the only ones in the record, but instead I have ~60 fields that I would group into categories such as MATERIALITY, PRODUCTION, CONTENT, ASSOCIATIONS, etc. Within each of those categorisations some fields could be in groups (e.g. artistMaker*) of which only 1 needs to have a value, so ideally I would like this:

| artistMakerPerson  | artistMakerOrganisation | artistMakerPeople | placesOfOrigin | PRODUCTION completeness | 
| ---- | ---- | ---- | ---- | ----- |
| 1 | 1 | 1 | 1 | 1 |
| 1 | 1 | 0 | 1 | 1 |
| 1 | 0 | 1 | 1 | 1 |
| 1 | 0 | 0 | 1 | 1 |
| 0 | 0 | 0 | 1 | 0.5 |
