### ISSUE TITLE
Inactive field creating categories

### ISSUE THREAD

**Issue by atiro** [pkiraly/metadata-qa-api#76]
Should a field marked as inactive still create a category if it's associated with it ? E.g.
```

    - name: contentWarning
      path: $.['contentWarning'][*].apprise
      categories:
          - CONTEXT
      inactive: true
```

still creates CONTEXT as SchemaFactory doesn't check active status.

(Again, discovered this while swapping files round and again could be argued that it shouldn't be in the category if it's inactive. But it might be useful to be able to turn on and off).
