### ISSUE TITLE
calculator.getHeader() returns extractable fields twice

### ISSUE THREAD

**Issue by mielvds** [pkiraly/metadata-qa-api#82]
Calling `calculator.getHeader()` on input like:

```json
{"recordId": "0000008c000a4b2cb90eefb7b131289d728fc57cc25946c2aca6ccb0820857da69f1ef620c2b4c99a668cb38062bf45c", "MDProperties.sp_name": "w1", "MDProperties.CP": "orgX", "MDProperties.PID": "2b8vb0bn5z", "MDProperties.dc_identifier_localid": "BR0000035282129", "MDProperties.CP_id": "OR-xxxxx", "MDProperties.dc_title": "BR0000035282129.tif"}
```

returns "recordId" twice, which makes it invalid as a (csv) header.

Schema:

```yaml
fields:
  - categories:
      - mandatory_if_present
    name: recordId
    path: $.['recordId']
    extractable: true
format: json
```
