### ISSUE TITLE
new rule: dimension

### ISSUE THREAD

**Issue by pkiraly** [pkiraly/metadata-qa-api#95]
This checks if a linked image fits to some dimension constraints (unit in pixel). One can check the minimum and maximum size of width, height and shorter or longer sides (in case it is not important if width or height is the shorter).

- minWidth: the minimum width
- maxWidth: the maximum width
- minHeight: minimum height
- maxHeight: maximum height
- minShortside: minimum length of the shorter side of the image
- maxShortside: maximum length of the shorter side of the image
- minLongside: minimum length of the longer side of the image
- maxLongside: minimum length of the longer side of the image

An example:
```yaml
format: csv
fields:
  - name: thumbnail
    path: oai:record/dc:identifier[@type='binary']
    rules:
      - id: 3.1
        failureScore: -9
        dimension:
          minWidth: 200
          minHeight: 200
```
